url: 'https://www.realestate.com.au/sold/property-apartment-vic-highett-124470098'
steps:
  - name: wait
    time: 1000
  - name: click
    selector: .property-info__bookmark
  - name: wait
    time: 2000
eventMatchers:
  - provider: AdobeAnalyticsAppMeasurement
    name: Save Property on Adobe
    snapshotFile: data/adobe/save_property.json
    ignoreParamKeysForComparison:
     - Browser time
     - Marketing Cloud Visitor ID
     - Prop72
     - sdid
     - eVar72
     - Legacy Visitor ID
    filters:
      - path: $.meta.title
        value: event62
  - provider: Snowplow
    name: Save Property on Snowplow
    snapshotFile: data/snowplow/save_property.json
    ignoreParamKeysForComparison:
      - dtm
      - eid
      - sid
      - stm
      - duid
    filters:
      - path: $.meta.title
        value: save_property
